name: Release (Main)

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write # to create release (changesets/action)
            pull-requests: write # to create pull request (changesets/action)
            id-token: write #  required for provenance and oidc publish
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  registry-url: "https://registry.npmjs.org"
            - name: update npm
              run: npm update -g npm
            - name: Install Dependencies
              run: yarn

            - name: Publish Release
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: yarn release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
